// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(naturalMongoSyntax) {
    var field, orderNum, sort;
    sort = [];
    for (field in naturalMongoSyntax) {
      orderNum = naturalMongoSyntax[field];
      sort.push([field, orderNum]);
    }
    return sort;
  };

}).call(this);
